name: 'Nrwl Nx'
author: 'Mansa Group'
description: 'Wrap the Nx monorepo tool and execute tasks depending on the action context'
inputs:
  working-directory:
    description: "The working directory of where to run the command."
    required: false
    default: ${{ github.workspace }}
  targets:
    description: "Comma-separated list of targets to execute"
    required: true
  projects:
    description: "Comma-separated list of projects to use"
    required: true
  all: # Mutualy exclusive with `affected`
    description: "Run the targets on all projects"
    required: false
    default: 'false'
  affected: # Mutualy exclusive with `all`
    description: "Use the Nx' affected subcommand to only process affected projects"
    required: false
    default: 'true'
  parallel:
    description: "Run the tasks in parallel (can be expensive)"
    required: false
    default: 'false'
  args:
    description: "Optional arguments to append to the Nx command"
    required: false
    default: ''
runs:
  using: 'composite'
  steps: 
    - run: ${{ github.action_path }}/script.sh
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_TARGETS: ${{ inputs.targets }}
        INPUT_PROJECTS: ${{ inputs.projects }}
        INPUT_ALL: ${{ inputs.all }}
        INPUT_AFFECTED: ${{ inputs.affected }}
        INPUT_PARALLEL: ${{ inputs.parallel }}
        INPUT_ARGS: ${{ inputs.args }}
        PR_BASE_REF_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_REF_SHA: ${{ github.event.pull_request.head.sha }}
branding:
  icon: 'terminal'
  color: 'blue'
